<?php
/**
 * @file
 * Code for the GSB Feature Featured Content FPP feature.
 */

include_once 'gsb_feature_featured_content_fpp.features.inc';

/**
 * Implements hook_form_alter().
 */
function gsb_feature_featured_content_fpp_form_alter(&$form, &$form_state, $form_id) {
  if (($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' || $form_id == 'fieldable_panels_panes_entity_edit_form')
     && $form_state['entity']->bundle == 'featured_content') {
    $form['title']['#access'] = FALSE;
    $form['field_featured_item']['#after_build'] = array('gsb_feature_featured_content_fpp_after_build');

    drupal_add_js(drupal_get_path('module', 'gsb_feature_featured_content_fpp') . '/js/gsb_feature_featured_content_fpp.js');

    // Perform additional validation.
    $form['#validate'][] = 'gsb_feature_featured_content_fpp_form_validate';
  }
}

/**
 * Validate callback for fpp.
 *  - Conditionally validate media format field.
 */
function gsb_feature_featured_content_fpp_form_validate($form, &$form_state) {
  $language = $form['language']['#value'];
  $values = $form_state['values'];
  foreach ($values['field_featured_item'][$language] as $key => $value) {
    if (is_numeric($key) && $key >= 0) {
      // If feature type is other is an media format is mandatory.
      if ($values['field_featured_item'][$language][$key]['field_feature_type'][$language][0]['value'] == 'other') {
        if (empty($values['field_featured_item'][$language][$key]['field_icon'][$language][0]['value'])) {
          $field_label = $form['field_featured_item'][$language][$key]['field_icon'][$language]['#title'];
          form_set_error('field_icon]['.$language.']['.$key.'][tid', $field_label . ' field is required.');
        }
        if (empty($values['field_featured_item'][$language][$key]['field_link_single'][$language][0]['url'])) {
          $field_label = $form['field_featured_item'][$language][$key]['field_link_single'][$language]['#title'];
          form_set_error('field_featured_item]['.$language.']['.$key.'][field_link_single]['.$language.']['.$key.'][url', $field_label . ' field is required.');
        }
        if (empty($values['field_featured_item'][$language][$key]['field_title'][$language][0]['value'])) {
          $field_label = $form['field_featured_item'][$language][$key]['field_title'][$language]['#title'];
          form_set_error('field_featured_item]['.$language.']['.$key.'][field_title]['.$language.']['.$key.'][value', $field_label . ' field is required.');
        }
      }
      if ($values['field_featured_item'][$language][$key]['field_feature_type'][$language][0]['value'] == 'nid') {
        $field_label = $form['field_featured_item'][$language][$key]['field_featured_content_fpp_ref'][$language]['#title'];
        form_set_error('field_featured_item]['.$language.']['.$key.'][field_featured_content_fpp_ref]['.$language.']['.$key.'][target_id', $field_label . ' field is required.');
      }
    }
  }
}

/**
 * gsb_feature_featured_content_fpp_after_build().
 */
function gsb_feature_featured_content_fpp_after_build($form, &$form_state) {
  foreach ($form[LANGUAGE_NONE] as $key => $value) {
    if (is_numeric($key) && $key >= 0) {

      // Add required field markers. The actual field validation is done in validate callback.
      if (!empty($form[LANGUAGE_NONE][$key]['field_icon'][LANGUAGE_NONE])) {
        $form[LANGUAGE_NONE][$key]['field_icon'][LANGUAGE_NONE]['#title'] .= " " . theme('form_required_marker');
      }

      // Remove N/A option from feature type and media format radio button
      unset($form[LANGUAGE_NONE][$key]['field_feature_type'][LANGUAGE_NONE]['#options']['_none']);
      unset($form[LANGUAGE_NONE][$key]['field_feature_type'][LANGUAGE_NONE]['_none']);

      unset($form[LANGUAGE_NONE][$key]['field_icon'][LANGUAGE_NONE]['#options']['_none']);
      unset($form[LANGUAGE_NONE][$key]['field_icon'][LANGUAGE_NONE]['_none']);

      // Change #id to apply #states.

      //field_featured_content_fpp_ref
      $form[LANGUAGE_NONE][$key]['field_featured_content_fpp_ref']['#states']['visible'] = array(
        ':input[name="field_featured_item[und]['.$key.'][field_feature_type][und]"]' => array('value' => 'nid'),
      );
      $form[LANGUAGE_NONE][$key]['field_featured_content_fpp_ref']['#states']['required'] = array(
        ':input[name="field_featured_item[und]['.$key.'][field_feature_type][und]"]' => array('value' => 'nid'),
      );

      // field_link_single
      $form[LANGUAGE_NONE][$key]['field_link_single']['#id'] = 'views-exposed-pane-other-link'.$key;
      $form[LANGUAGE_NONE][$key]['field_link_single']['#states']['visible'] = array(
        ':input[name="field_featured_item[und]['.$key.'][field_feature_type][und]"]' => array('value' => 'other'),
      );
      $form[LANGUAGE_NONE][$key]['field_link_single']['#states']['required'] = array(
        ':input[name="field_featured_item[und]['.$key.'][field_feature_type][und]"]' => array('value' => 'other'),
      );

      // field_icon
      $form[LANGUAGE_NONE][$key]['field_icon']['#id'] = 'views-exposed-pane-other-icon'.$key;
      $form[LANGUAGE_NONE][$key]['field_icon']['#states'] = array(
        'visible' => array(
          ':input[name="field_featured_item[und]['.$key.'][field_feature_type][und]"]' => array('value' => 'other'),
        ),
      );

      // field_title
      $form[LANGUAGE_NONE][$key]['field_title']['#id'] = 'views-exposed-pane-other-title'.$key;
      $form[LANGUAGE_NONE][$key]['field_title']['#states']['visible'] = array(
        ':input[name="field_featured_item[und]['.$key.'][field_feature_type][und]"]' => array('value' => 'other'),
      );
      $form[LANGUAGE_NONE][$key]['field_title']['#states']['required'] = array(
        ':input[name="field_featured_item[und]['.$key.'][field_feature_type][und]"]' => array('value' => 'other'),
      );

    }
  }

  return $form;
}

/**
 * Implements hook_field_collection_item_view().
 */
function gsb_feature_featured_content_fpp_field_collection_item_view($field_collection_item, $view_mode, $langcode) {
 if(isset($field_collection_item->field_feature_type)){
    if ($field_collection_item->field_feature_type[LANGUAGE_NONE][0]['value'] == 'other') {
     $field_collection_item->content['field_title'][0]['#markup'] = '<a href='.$field_collection_item->field_link_single[LANGUAGE_NONE][0]['url'].'>'.$field_collection_item->content['field_title'][0]['#markup'].'</a>';
    }
  }
}
